server:
    port: 8085
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: vakporize
        url: jdbc:mysql://localhost:3306/java_dcbapp
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
welcome:
    message:
        config: Welcome to Daily Code Buffer with learnings as VAX
